### PR TITLE
chore(webtransport): Add interop-tests support with wasm

### PR DESCRIPTION
**Pull request by zvolin**
## Description

Add interop tests for webtransport backend. The test is built as a wasm package and executed in headless chrome instance using webdriver.

Related #4065.

## Notes & open questions

I've tested this both locally and from within the docker image versus the go-libp2p ping implementation.

This still needs to be picked up in https://github.com/libp2p/test-plans/blob/master/multidim-interop/versions.ts

I'm not sure how should I modify the `ping-version.json` file.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works (this itself is a test)
- [x] A changelog entry has been made in the appropriate crates (changelog added in @oblique PR's)

### CODE REVIEW

**Comment by zvolin** [comment]
Also discussed there https://github.com/libp2p/rust-libp2p/pull/4063

**Comment by thomaseizinger** [comment]
This is ready from my end. Next steps are:

- [x] Merge this PR
- [x] Close https://github.com/libp2p/rust-libp2p/pull/4063
- [x] Merge https://github.com/libp2p/rust-libp2p/pull/4069 to ensure proper attribution
- [x] Do a final review of https://github.com/libp2p/rust-libp2p/pull/4015
- [x] Update the name of the required jobs: https://github.com/libp2p/github-mgmt/blob/master/github/libp2p.yml#L6963
- [x] Merge https://github.com/libp2p/rust-libp2p/pull/4015

**Comment by thomaseizinger** [comment]
My suggestion would be to squash-merge this PR because it has a lot of merge commits in it already @oblique.

**Comment by oblique** [comment]
@thomaseizinger  Question about squash merge: Because there was a merge with `master` branch, I get a lot of `Co-authored-by:` that are not related with the PR itself. Do I remove them or keep them?

**Comment by thomaseizinger** [comment]
> @thomaseizinger Question about squash merge: Because there was a merge with `master` branch, I get a lot of `Co-authored-by:` that are not related with the PR itself. Do I remove them or keep them?

Remove them please!

**Comment by thomaseizinger** [comment]
Fingers crossed my two follow-up commits didn't break the interop tests now :see_no_evil:

**Pull request merged**
